insert_api_key = "Please insert BOT_API_KEY:"
install_modules = "Try command: pip install -r requirements.txt"
setup_header = "=== SETUP ==="
incorrect_token = "Current token is incorrect, ensure that you copied it right"
checking_modules = "- checking modules"
chacking_key = "- checking key"
success = "SUCCESS"
fail = "FAIL"
setup_done = "=== SETUP DONE ==="
setup_fail = "=== SETUP FAIL ==="
api_key_is = "API KEY IS: "
key_path = "../materials/text/api_key.txt"
key_not_found = fail
setup_status = "SETUP_STATUS: "
try_setup = 'Try run "python setup.py"'
